### ISSUE TITLE
[Feature] Add support for `mongodb` database

### ISSUE THREAD

**Issue by barthofu** [barthofu/tscord#16]
### Feature?

And more generaly for NoSQL databases.
We could also think to Redis, etc.

**Comment by barthofu** [comment]
N.B: this branch will be in stand by till we know how to implement it in the CLI template generate (`create-tscord-bot`)
It will also be useful for the writing of the documentation.

**Comment by ElMehdiBouamama** [comment]
You probably don't need to implement a NOSQL database because the currently implemented database supports the EAV pattern which allows to store key/value pairs just like you would do in a NOSQL database.

Documentation about the currently available EAV pattern from discordx bellow:
https://barthofu.github.io/tscord-docs/docs/bot/features/database/single-data-type
